{{- if ((.Values.odfSslCertificateExtractor | default dict).enabled | default false) }}
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-odf-ssl-hub
  namespace: open-cluster-management
  labels:
    app.kubernetes.io/name: odf-ssl-certificate-management
    app.kubernetes.io/component: placement
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "3"
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - local-cluster
{{- end }}
